version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ResumenCuentaTOML"
s3_bucket = "resumen-cuenta-lambdas-source"
s3_prefix = "ResumenCuentaSource"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
