AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Spliiter de Resumen de cuentas

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 8
      Variables:
        CORE_LAMBDA: CoreLmabdaTESTtest

Resources:
  Splitter:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: splitter
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Events:
        S3Event:
          Type: S3
          Properties:
              Bucket:
                Ref: resumenCuentaS3
              Events:
                - 's3:ObjectCreated:*'
              Filter:
                S3Key:
                  Rules:
                    - Name: prefix
                      Value: input/
                    - Name: suffix
                      Value: .csv
  resumenCuentaS3:
    Type: 'AWS::S3::Bucket'

#Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  #Splitter:
  #  Description: "Hello World Lambda Function ARN"
  #  Value: !GetAtt Splitter.Arn
  #SplitterIamRole:
  #  Description: "Implicit IAM Role created for Hello World function"
  #  Value: !GetAtt SplitterRole.Arn
