AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Core de Resumen de cuentas

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 8

Resources:
  Core:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64

#Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  #Core:
  #  Description: "Hello World Lambda Function ARN"
  #  Value: !GetAtt Core.Arn
  #CoreIamRole:
  #  Description: "Implicit IAM Role created for Hello World function"
  #  Value: !GetAtt CoreRole.Arn
